SELECT * FROM MATRIZ_CLIENTES WHERE CODCLISAC = '01783039000195'
SELECT * FROM DADOS_CLIENTES_GERAL WHERE CODCLI = '22371' AND CGC = '84046101026400'
SELECT * FROM CLIENTES_GERAL WHERE CODCLI = '22371' AND CGC = '19813226803'            

SELECT DISTINCT
		A.CODCLISAC as CODCLI_SARWIN,
		B.TIPO_PESSOA AS A1_PESSOA,
		SUBSTRING (A.CPF_CNPJ,1,14) as A1_CGC,  
		SUBSTRING (A.CPF_CNPJ, 1 , 8 ) as A1_CODIGO, 
		SUBSTRING (A.CPF_CNPJ, 9 , 4 ) as A1_LOJA,
		B.INSCEST as A1_INSCR,
		B.NOMESACADO as A1_NOME,
		B.NOMESACADO as A1_NREDUZ,
		B.PRACAPAG as A1_END,
		B.BAIRROPAG as A1_BAIRRO,
		B.ESTADOPAG as A1_EST,
		B.CEPPAG as A1_CEP,
		B.MUNICIPPAG as A1_MUN,
		C.CODCLI as CODCLI_SARWIN,
		C.TIPO AS A1_PESSOA,
		SUBSTRING (B.CGC,1,14) as A1_CGC,  
		SUBSTRING (B.CGC, 1 , 8 ) as A1_CODIGO, 
		SUBSTRING (B.CGC, 9 , 4 ) as A1_LOJA,
		C.INSCEST as A1_INSCR,
		C.NOMESACADO as A1_NOME,
		C.NOMESACADO as A1_NREDUZ,
		C.PRACAPAG as A1_END,
		C.BAIRROPAG as A1_BAIRRO,
		C.ESTADOPAG as A1_EST,
		C.CEPPAG as A1_CEP,
		C.MUNICIPPAG as A1_MUN

FROM MATRIZ_CLIENTES A
LEFT JOIN DADOS_CLIENTES_GERAL B ON A.CODCLISAC = B.CODCLI AND A.CPF_CNPJ = B.CGC
LEFT JOIN CLIENTES_GERAL C ON A.CODCLISAC = C.CODCLI AND A.CPF_CNPJ = C.CGC
WHERE A.CODCLISAC = '22371'
