/****** Script do comando SelectTopNRows de SSMS  ******/
SELECT DISTINCT 
		A.CODCLI as CLIENTE_SARWIN,
		A.CODPOS as POSTO_SARWIN,
		A.CODGRU as GRUPO_SARWIN,
	    SUBSTRING (E.CGC, 1 , 8 ) as ABS_CODIGO_A, 
		SUBSTRING (E.CGC, 11 , 4 ) as ABS_LOJA_A, 
		SUBSTRING (F.CGC, 1 , 8 ) as ABS_CODIGO_B, 
		SUBSTRING (F.CGC, 11 , 4 ) as ABS_LOJA_B, 
		A.NOMEPOS as ABS_DESCRI,
		E.NOMEGRU as ABS_DESCRI_B,
		E.NOMESACADO as ABS_DESCRI_C,
		(CONCAT(RTRIM(C.ENDERECO),', ',RTRIM(C.NUMERO), ' ', C.COMPLEMENT)) AS ABS_END, 
		C.BAIRRO as ABS_BAIRRO,
		C.CEP as ABS_CEP,
		F.ESTADOPAG as ABS_ESTADO,
		D.IBGE as ABS_CODMUN,
		D.NOMECID as ABS_MUNIC,
		C.TELEFONE as ABS_XTEL,
		C.EMAIL AS ABS_EMAIL,
		C.ZONA as ABS_REGIAO,
		A.EMPRESA as A1_FILIAL,
		SUBSTRING (F.CGC, 1 , 8 ) as ABS_CLIFAT, 
		SUBSTRING (F.CGC, 11 , 4 ) as ABS_LJFAT

FROM SARPOSTO_GERAL A
INNER JOIN SARRLEND_GERAL B ON A.CODCLI = B.CODCLI AND A.CODPOS = B.CODPOS AND A.EMPRESA = B.FILIAL
LEFT JOIN SARENDCL_GERAL C ON C.CODCLI = A.CODCLI AND C.FILIAL = A.EMPRESA AND C.CODEND = B.CODEND
LEFT JOIN SARCIDADES_GERAL D ON D.CODCID = C.CODCID
LEFT JOIN SFGRUPO_GERAL E ON E.CODCLI = A.CODCLI AND E.CODGRU = A.CODGRU  AND E.CODCID = D.CODCID AND A.EMPRESA = E.FILIAL
LEFT JOIN SARCLI_GERAL F ON F.CODCLI = A.CODCLI AND F.FILIAL = A.EMPRESA --F.CGC <> E.CGC AND 
WHERE A.CODCLI NOT IN( '20350','1000', '-1', '16000', '20340', '20011', '20341', '20342', '20343', '20348', '20349', '22149', '629', '477', '23159', '22378', '22367', '22131')

/*
SELECT * FROM SFGRUPO_GERAL WHERE  CODCLI ='22015' AND CODGRU = '13'

SELECT * FROM SARCLI_GERAL WHERE  CODCLI = '20113' --F

SELECT * FROM SARCLI_GERAL WHERE FILIAL = '7' AND CODCLI = '20071'--Refazer RJ

SELECT * FROM SARPOSTO_GERAL WHERE CODCLI = '20068' AND CODPOS = '2001' --A
SELECT * FROM SARPOSTO_GERAL WHERE CODCLI ='22015' AND CODGRU = '13'

SELECT * FROM SARRLEND_GERAL WHERE CODCLI = '20071' AND CODPOS = '2001' --AND CODEND = '638' --B


SELECT * FROM SARENDCL_GERAL WHERE CODCLI = '20071' AND CODEND IN ('638','3') --C 3 - 638

SELECT * FROM SARCIDADES_GERAL WHERE CODCID IN ('5231', '3529') --D
*/


                                                                                                                                        